//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperGear.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
    
        public int MaSP { get; set; }
        [Display(Name = "Tên Sản Phẩm")]
        public string TenSP { get; set; }
        [Display(Name = "Giá")]
        public Nullable<decimal> Gia { get; set; }
        public string Slug { get; set; }
        [Display(Name = "Mô Tả")]
        public string Mota { get; set; }
        [Display(Name = "Chi Tiết")]
        public string ChiTiet { get; set; }
        [Display(Name = "Ảnh")]
        public string Anh { get; set; }
        public Nullable<System.DateTime> Ngaycapnhat { get; set; }
        public Nullable<int> Soluongton { get; set; }
        public Nullable<int> MaDM { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public string Updated_by { get; set; }
        [Display(Name = "Trạng Thái")]
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
    }
}
