//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyperGear.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TinTuc
    {
        public int MaTT { get; set; }
        [Display(Name = "Tiêu Đề")]
        public string TieuDe { get; set; }
        [Display(Name = "Nội Dung")]
        public string NoiDung { get; set; }
        [Display(Name = "Ảnh")]
        public string Anh { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> Updated_at { get; set; }
        public string Updated_by { get; set; }
        public Nullable<int> Status { get; set; }
        public string Slug { get; set; }
    }
}
